<?php

/**
 * Base class that represents a row from the 'customer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Jul 14 12:51:39 2009
 *
 * @package    lib.model.om
 */
abstract class BaseCustomer extends BaseObject  implements Persistent {


  const PEER = 'CustomerPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        CustomerPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the surname field.
	 * @var        string
	 */
	protected $surname;

	/**
	 * The value for the municipality field.
	 * @var        string
	 */
	protected $municipality;

	/**
	 * The value for the address field.
	 * @var        string
	 */
	protected $address;

	/**
	 * The value for the zip field.
	 * @var        string
	 */
	protected $zip;

	/**
	 * The value for the phone field.
	 * @var        string
	 */
	protected $phone;

	/**
	 * The value for the mobile field.
	 * @var        string
	 */
	protected $mobile;

	/**
	 * The value for the newmunicipality field.
	 * @var        string
	 */
	protected $newmunicipality;

	/**
	 * The value for the offer_id field.
	 * @var        int
	 */
	protected $offer_id;

	/**
	 * The value for the type_id field.
	 * @var        int
	 */
	protected $type_id;

	/**
	 * The value for the typology_id field.
	 * @var        int
	 */
	protected $typology_id;

	/**
	 * The value for the bedroom field.
	 * @var        int
	 */
	protected $bedroom;

	/**
	 * The value for the bath field.
	 * @var        int
	 */
	protected $bath;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the maxprice field.
	 * @var        double
	 */
	protected $maxprice;

	/**
	 * The value for the is_active field.
	 * Note: this column has a database default value of: true
	 * @var        boolean
	 */
	protected $is_active;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        Offer
	 */
	protected $aOffer;

	/**
	 * @var        Type
	 */
	protected $aType;

	/**
	 * @var        Typology
	 */
	protected $aTypology;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseCustomer object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->is_active = true;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [surname] column value.
	 * 
	 * @return     string
	 */
	public function getSurname()
	{
		return $this->surname;
	}

	/**
	 * Get the [municipality] column value.
	 * 
	 * @return     string
	 */
	public function getMunicipality()
	{
		return $this->municipality;
	}

	/**
	 * Get the [address] column value.
	 * 
	 * @return     string
	 */
	public function getAddress()
	{
		return $this->address;
	}

	/**
	 * Get the [zip] column value.
	 * 
	 * @return     string
	 */
	public function getZip()
	{
		return $this->zip;
	}

	/**
	 * Get the [phone] column value.
	 * 
	 * @return     string
	 */
	public function getPhone()
	{
		return $this->phone;
	}

	/**
	 * Get the [mobile] column value.
	 * 
	 * @return     string
	 */
	public function getMobile()
	{
		return $this->mobile;
	}

	/**
	 * Get the [newmunicipality] column value.
	 * 
	 * @return     string
	 */
	public function getNewmunicipality()
	{
		return $this->newmunicipality;
	}

	/**
	 * Get the [offer_id] column value.
	 * 
	 * @return     int
	 */
	public function getOfferId()
	{
		return $this->offer_id;
	}

	/**
	 * Get the [type_id] column value.
	 * 
	 * @return     int
	 */
	public function getTypeId()
	{
		return $this->type_id;
	}

	/**
	 * Get the [typology_id] column value.
	 * 
	 * @return     int
	 */
	public function getTypologyId()
	{
		return $this->typology_id;
	}

	/**
	 * Get the [bedroom] column value.
	 * 
	 * @return     int
	 */
	public function getBedroom()
	{
		return $this->bedroom;
	}

	/**
	 * Get the [bath] column value.
	 * 
	 * @return     int
	 */
	public function getBath()
	{
		return $this->bath;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [maxprice] column value.
	 * 
	 * @return     double
	 */
	public function getMaxprice()
	{
		return $this->maxprice;
	}

	/**
	 * Get the [is_active] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsActive()
	{
		return $this->is_active;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = CustomerPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = CustomerPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [surname] column.
	 * 
	 * @param      string $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setSurname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->surname !== $v) {
			$this->surname = $v;
			$this->modifiedColumns[] = CustomerPeer::SURNAME;
		}

		return $this;
	} // setSurname()

	/**
	 * Set the value of [municipality] column.
	 * 
	 * @param      string $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setMunicipality($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->municipality !== $v) {
			$this->municipality = $v;
			$this->modifiedColumns[] = CustomerPeer::MUNICIPALITY;
		}

		return $this;
	} // setMunicipality()

	/**
	 * Set the value of [address] column.
	 * 
	 * @param      string $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setAddress($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->address !== $v) {
			$this->address = $v;
			$this->modifiedColumns[] = CustomerPeer::ADDRESS;
		}

		return $this;
	} // setAddress()

	/**
	 * Set the value of [zip] column.
	 * 
	 * @param      string $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setZip($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->zip !== $v) {
			$this->zip = $v;
			$this->modifiedColumns[] = CustomerPeer::ZIP;
		}

		return $this;
	} // setZip()

	/**
	 * Set the value of [phone] column.
	 * 
	 * @param      string $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setPhone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->phone !== $v) {
			$this->phone = $v;
			$this->modifiedColumns[] = CustomerPeer::PHONE;
		}

		return $this;
	} // setPhone()

	/**
	 * Set the value of [mobile] column.
	 * 
	 * @param      string $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setMobile($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mobile !== $v) {
			$this->mobile = $v;
			$this->modifiedColumns[] = CustomerPeer::MOBILE;
		}

		return $this;
	} // setMobile()

	/**
	 * Set the value of [newmunicipality] column.
	 * 
	 * @param      string $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setNewmunicipality($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->newmunicipality !== $v) {
			$this->newmunicipality = $v;
			$this->modifiedColumns[] = CustomerPeer::NEWMUNICIPALITY;
		}

		return $this;
	} // setNewmunicipality()

	/**
	 * Set the value of [offer_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setOfferId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->offer_id !== $v) {
			$this->offer_id = $v;
			$this->modifiedColumns[] = CustomerPeer::OFFER_ID;
		}

		if ($this->aOffer !== null && $this->aOffer->getId() !== $v) {
			$this->aOffer = null;
		}

		return $this;
	} // setOfferId()

	/**
	 * Set the value of [type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->type_id !== $v) {
			$this->type_id = $v;
			$this->modifiedColumns[] = CustomerPeer::TYPE_ID;
		}

		if ($this->aType !== null && $this->aType->getId() !== $v) {
			$this->aType = null;
		}

		return $this;
	} // setTypeId()

	/**
	 * Set the value of [typology_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setTypologyId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->typology_id !== $v) {
			$this->typology_id = $v;
			$this->modifiedColumns[] = CustomerPeer::TYPOLOGY_ID;
		}

		if ($this->aTypology !== null && $this->aTypology->getId() !== $v) {
			$this->aTypology = null;
		}

		return $this;
	} // setTypologyId()

	/**
	 * Set the value of [bedroom] column.
	 * 
	 * @param      int $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setBedroom($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->bedroom !== $v) {
			$this->bedroom = $v;
			$this->modifiedColumns[] = CustomerPeer::BEDROOM;
		}

		return $this;
	} // setBedroom()

	/**
	 * Set the value of [bath] column.
	 * 
	 * @param      int $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setBath($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->bath !== $v) {
			$this->bath = $v;
			$this->modifiedColumns[] = CustomerPeer::BATH;
		}

		return $this;
	} // setBath()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = CustomerPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [maxprice] column.
	 * 
	 * @param      double $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setMaxprice($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->maxprice !== $v) {
			$this->maxprice = $v;
			$this->modifiedColumns[] = CustomerPeer::MAXPRICE;
		}

		return $this;
	} // setMaxprice()

	/**
	 * Set the value of [is_active] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setIsActive($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_active !== $v || $v === true) {
			$this->is_active = $v;
			$this->modifiedColumns[] = CustomerPeer::IS_ACTIVE;
		}

		return $this;
	} // setIsActive()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CustomerPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Customer The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CustomerPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(CustomerPeer::IS_ACTIVE))) {
				return false;
			}

			if ($this->is_active !== true) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->surname = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->municipality = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->address = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->zip = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->phone = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->mobile = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->newmunicipality = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->offer_id = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->type_id = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->typology_id = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->bedroom = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->bath = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->description = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->maxprice = ($row[$startcol + 15] !== null) ? (double) $row[$startcol + 15] : null;
			$this->is_active = ($row[$startcol + 16] !== null) ? (boolean) $row[$startcol + 16] : null;
			$this->created_at = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->updated_at = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 19; // 19 = CustomerPeer::NUM_COLUMNS - CustomerPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Customer object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aOffer !== null && $this->offer_id !== $this->aOffer->getId()) {
			$this->aOffer = null;
		}
		if ($this->aType !== null && $this->type_id !== $this->aType->getId()) {
			$this->aType = null;
		}
		if ($this->aTypology !== null && $this->typology_id !== $this->aTypology->getId()) {
			$this->aTypology = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CustomerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = CustomerPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aOffer = null;
			$this->aType = null;
			$this->aTypology = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCustomer:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CustomerPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			CustomerPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseCustomer:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseCustomer:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(CustomerPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(CustomerPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CustomerPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseCustomer:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			CustomerPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aOffer !== null) {
				if ($this->aOffer->isModified() || $this->aOffer->isNew()) {
					$affectedRows += $this->aOffer->save($con);
				}
				$this->setOffer($this->aOffer);
			}

			if ($this->aType !== null) {
				if ($this->aType->isModified() || $this->aType->isNew()) {
					$affectedRows += $this->aType->save($con);
				}
				$this->setType($this->aType);
			}

			if ($this->aTypology !== null) {
				if ($this->aTypology->isModified() || $this->aTypology->isNew()) {
					$affectedRows += $this->aTypology->save($con);
				}
				$this->setTypology($this->aTypology);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = CustomerPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = CustomerPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += CustomerPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aOffer !== null) {
				if (!$this->aOffer->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aOffer->getValidationFailures());
				}
			}

			if ($this->aType !== null) {
				if (!$this->aType->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aType->getValidationFailures());
				}
			}

			if ($this->aTypology !== null) {
				if (!$this->aTypology->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTypology->getValidationFailures());
				}
			}


			if (($retval = CustomerPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CustomerPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getSurname();
				break;
			case 3:
				return $this->getMunicipality();
				break;
			case 4:
				return $this->getAddress();
				break;
			case 5:
				return $this->getZip();
				break;
			case 6:
				return $this->getPhone();
				break;
			case 7:
				return $this->getMobile();
				break;
			case 8:
				return $this->getNewmunicipality();
				break;
			case 9:
				return $this->getOfferId();
				break;
			case 10:
				return $this->getTypeId();
				break;
			case 11:
				return $this->getTypologyId();
				break;
			case 12:
				return $this->getBedroom();
				break;
			case 13:
				return $this->getBath();
				break;
			case 14:
				return $this->getDescription();
				break;
			case 15:
				return $this->getMaxprice();
				break;
			case 16:
				return $this->getIsActive();
				break;
			case 17:
				return $this->getCreatedAt();
				break;
			case 18:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = CustomerPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getSurname(),
			$keys[3] => $this->getMunicipality(),
			$keys[4] => $this->getAddress(),
			$keys[5] => $this->getZip(),
			$keys[6] => $this->getPhone(),
			$keys[7] => $this->getMobile(),
			$keys[8] => $this->getNewmunicipality(),
			$keys[9] => $this->getOfferId(),
			$keys[10] => $this->getTypeId(),
			$keys[11] => $this->getTypologyId(),
			$keys[12] => $this->getBedroom(),
			$keys[13] => $this->getBath(),
			$keys[14] => $this->getDescription(),
			$keys[15] => $this->getMaxprice(),
			$keys[16] => $this->getIsActive(),
			$keys[17] => $this->getCreatedAt(),
			$keys[18] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CustomerPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setSurname($value);
				break;
			case 3:
				$this->setMunicipality($value);
				break;
			case 4:
				$this->setAddress($value);
				break;
			case 5:
				$this->setZip($value);
				break;
			case 6:
				$this->setPhone($value);
				break;
			case 7:
				$this->setMobile($value);
				break;
			case 8:
				$this->setNewmunicipality($value);
				break;
			case 9:
				$this->setOfferId($value);
				break;
			case 10:
				$this->setTypeId($value);
				break;
			case 11:
				$this->setTypologyId($value);
				break;
			case 12:
				$this->setBedroom($value);
				break;
			case 13:
				$this->setBath($value);
				break;
			case 14:
				$this->setDescription($value);
				break;
			case 15:
				$this->setMaxprice($value);
				break;
			case 16:
				$this->setIsActive($value);
				break;
			case 17:
				$this->setCreatedAt($value);
				break;
			case 18:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = CustomerPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setSurname($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setMunicipality($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setAddress($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setZip($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPhone($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setMobile($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setNewmunicipality($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setOfferId($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setTypeId($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setTypologyId($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setBedroom($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setBath($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setDescription($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setMaxprice($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setIsActive($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setCreatedAt($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setUpdatedAt($arr[$keys[18]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(CustomerPeer::DATABASE_NAME);

		if ($this->isColumnModified(CustomerPeer::ID)) $criteria->add(CustomerPeer::ID, $this->id);
		if ($this->isColumnModified(CustomerPeer::NAME)) $criteria->add(CustomerPeer::NAME, $this->name);
		if ($this->isColumnModified(CustomerPeer::SURNAME)) $criteria->add(CustomerPeer::SURNAME, $this->surname);
		if ($this->isColumnModified(CustomerPeer::MUNICIPALITY)) $criteria->add(CustomerPeer::MUNICIPALITY, $this->municipality);
		if ($this->isColumnModified(CustomerPeer::ADDRESS)) $criteria->add(CustomerPeer::ADDRESS, $this->address);
		if ($this->isColumnModified(CustomerPeer::ZIP)) $criteria->add(CustomerPeer::ZIP, $this->zip);
		if ($this->isColumnModified(CustomerPeer::PHONE)) $criteria->add(CustomerPeer::PHONE, $this->phone);
		if ($this->isColumnModified(CustomerPeer::MOBILE)) $criteria->add(CustomerPeer::MOBILE, $this->mobile);
		if ($this->isColumnModified(CustomerPeer::NEWMUNICIPALITY)) $criteria->add(CustomerPeer::NEWMUNICIPALITY, $this->newmunicipality);
		if ($this->isColumnModified(CustomerPeer::OFFER_ID)) $criteria->add(CustomerPeer::OFFER_ID, $this->offer_id);
		if ($this->isColumnModified(CustomerPeer::TYPE_ID)) $criteria->add(CustomerPeer::TYPE_ID, $this->type_id);
		if ($this->isColumnModified(CustomerPeer::TYPOLOGY_ID)) $criteria->add(CustomerPeer::TYPOLOGY_ID, $this->typology_id);
		if ($this->isColumnModified(CustomerPeer::BEDROOM)) $criteria->add(CustomerPeer::BEDROOM, $this->bedroom);
		if ($this->isColumnModified(CustomerPeer::BATH)) $criteria->add(CustomerPeer::BATH, $this->bath);
		if ($this->isColumnModified(CustomerPeer::DESCRIPTION)) $criteria->add(CustomerPeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(CustomerPeer::MAXPRICE)) $criteria->add(CustomerPeer::MAXPRICE, $this->maxprice);
		if ($this->isColumnModified(CustomerPeer::IS_ACTIVE)) $criteria->add(CustomerPeer::IS_ACTIVE, $this->is_active);
		if ($this->isColumnModified(CustomerPeer::CREATED_AT)) $criteria->add(CustomerPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(CustomerPeer::UPDATED_AT)) $criteria->add(CustomerPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(CustomerPeer::DATABASE_NAME);

		$criteria->add(CustomerPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Customer (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setSurname($this->surname);

		$copyObj->setMunicipality($this->municipality);

		$copyObj->setAddress($this->address);

		$copyObj->setZip($this->zip);

		$copyObj->setPhone($this->phone);

		$copyObj->setMobile($this->mobile);

		$copyObj->setNewmunicipality($this->newmunicipality);

		$copyObj->setOfferId($this->offer_id);

		$copyObj->setTypeId($this->type_id);

		$copyObj->setTypologyId($this->typology_id);

		$copyObj->setBedroom($this->bedroom);

		$copyObj->setBath($this->bath);

		$copyObj->setDescription($this->description);

		$copyObj->setMaxprice($this->maxprice);

		$copyObj->setIsActive($this->is_active);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Customer Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     CustomerPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new CustomerPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Offer object.
	 *
	 * @param      Offer $v
	 * @return     Customer The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setOffer(Offer $v = null)
	{
		if ($v === null) {
			$this->setOfferId(NULL);
		} else {
			$this->setOfferId($v->getId());
		}

		$this->aOffer = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Offer object, it will not be re-added.
		if ($v !== null) {
			$v->addCustomer($this);
		}

		return $this;
	}


	/**
	 * Get the associated Offer object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Offer The associated Offer object.
	 * @throws     PropelException
	 */
	public function getOffer(PropelPDO $con = null)
	{
		if ($this->aOffer === null && ($this->offer_id !== null)) {
			$c = new Criteria(OfferPeer::DATABASE_NAME);
			$c->add(OfferPeer::ID, $this->offer_id);
			$this->aOffer = OfferPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aOffer->addCustomers($this);
			 */
		}
		return $this->aOffer;
	}

	/**
	 * Declares an association between this object and a Type object.
	 *
	 * @param      Type $v
	 * @return     Customer The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setType(Type $v = null)
	{
		if ($v === null) {
			$this->setTypeId(NULL);
		} else {
			$this->setTypeId($v->getId());
		}

		$this->aType = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Type object, it will not be re-added.
		if ($v !== null) {
			$v->addCustomer($this);
		}

		return $this;
	}


	/**
	 * Get the associated Type object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Type The associated Type object.
	 * @throws     PropelException
	 */
	public function getType(PropelPDO $con = null)
	{
		if ($this->aType === null && ($this->type_id !== null)) {
			$c = new Criteria(TypePeer::DATABASE_NAME);
			$c->add(TypePeer::ID, $this->type_id);
			$this->aType = TypePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aType->addCustomers($this);
			 */
		}
		return $this->aType;
	}

	/**
	 * Declares an association between this object and a Typology object.
	 *
	 * @param      Typology $v
	 * @return     Customer The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTypology(Typology $v = null)
	{
		if ($v === null) {
			$this->setTypologyId(NULL);
		} else {
			$this->setTypologyId($v->getId());
		}

		$this->aTypology = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Typology object, it will not be re-added.
		if ($v !== null) {
			$v->addCustomer($this);
		}

		return $this;
	}


	/**
	 * Get the associated Typology object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Typology The associated Typology object.
	 * @throws     PropelException
	 */
	public function getTypology(PropelPDO $con = null)
	{
		if ($this->aTypology === null && ($this->typology_id !== null)) {
			$c = new Criteria(TypologyPeer::DATABASE_NAME);
			$c->add(TypologyPeer::ID, $this->typology_id);
			$this->aTypology = TypologyPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTypology->addCustomers($this);
			 */
		}
		return $this->aTypology;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aOffer = null;
			$this->aType = null;
			$this->aTypology = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseCustomer:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseCustomer::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseCustomer
